export enum ProductList  {
    REQUEST =  "PRODUCT_LIST_REQUEST",
    SUCCESS =  "PRODUCT_LIST_SUCCESS",
    FAIL =  "PRODUCT_LIST_FAIL",
}
    

export enum ProductDetail  {
    REQUEST =  "PRODUCT_DETAIL_REQUEST",
    SUCCESS =  "PRODUCT_DETAIL_SUCCESS",
    FAIL =  "PRODUCT_DETAIL_FAIL",
}
    
export enum AddToCart {
    ADD = "ADD_TO_CART",
    REMOVE = "REMOVE_TO_CART",
    SAVE_SHIPPING = "SAVE_SHIPPING_ADDRES",
    SAVE_PAYMENT=  "SAVE_PAYMENT_METHOD",
    CALCULATE_PRICE = "CALCULATE_TOTAL_PRICE"

}



export enum UserSingIn  {
    LOGOUT = 'USER_LOGOUT',

    REQUEST =  "USER_DETAIL_REQUEST",
    SUCCESS =  "USER_DETAIL_SUCCESS",
    FAIL =  "USER_DETAIL_FAIL",
}


export enum UserSingUp  {

    REQUEST =  "USER_SIGN_UP_REQUEST",
    SUCCESS =  "USER_SIGN_UP_SUCCESS",
    FAIL =  "USER_SIGN_UP_FAIL",
}