export enum ProductList  {
    REQUEST =  "PRODUCT_LIST_REQUEST",
    SUCCESS =  "PRODUCT_LIST_SUCCESS",
    FAIL =  "PRODUCT_LIST_FAIL",
}
    

export enum ProductDetail  {
    REQUEST =  "PRODUCT_DETAIL_REQUEST",
    SUCCESS =  "PRODUCT_DETAIL_SUCCESS",
    FAIL =  "PRODUCT_DETAIL_FAIL",
}